### ISSUE TITLE
Failure node does not include message and type attributes

### ISSUE THREAD

**Issue by rkpareek** [michaelleeallen/mocha-junit-reporter#63] opened 2018-07-18 11:02 UTC
```
it("\n1, test Cases...", function (done) {

            .get('https://google.com')
            .end(function (err, res) {
                if (!err) {                    
		      chai.expect(res.statusCode, res.error).to.have.property('data', 'Value', 'This is an error message when fails.');
                  done();
                }
                else
                    throw err;
            });
    });


The XML report:

 failure![CDATA[AssertionError [ERR_ASSERTION]: This is an error message when fails.
    at Test\test-apis\RaaS-V2\Authentication-Apis\Access-Token-Validation-Apis\GetCheckTokenValidity.js:58:24
    at pass_cb (Test\utility-modules\request-controller.js:76:17)
    at Test.<anonymous> (Test\utility-modules\request-controller.js:79:13)
    at Test.assert (node_modules\supertest\lib\test.js:179:6)
    at assert (node_modules\supertest\lib\test.js:131:12)
    at node_modules\supertest\lib\test.js:128:5
    at Test.Request.callback (node_modules\superagent\lib\node\index.js:718:3)
    at parser (node_modules\superagent\lib\node\index.js:906:18)
    at Stream.res.on (node_modules\superagent\lib\node\parsers\json.js:19:7)
    at Unzip.unzip.on (node_modules\superagent\lib\node\unzip.js:55:12)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)]]/failure

```

The error message "This is an error message when fails." should show in attribute of failure tag.

failure message="This is an error message when fails." stack trace    failure

**Comment by clayreimann** [comment] 2018-07-24 02:14
Can you provide a minimal reproducible example so we can see the behavior? You didn’t include enough detail here

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by clayreimann** [comment] 2018-07-25 19:33
Maybe I'm still confused, but this looks like expected behavior to me. You've provided `chai` with an explicit message for an assertion failure and that is flowing down into the report. If you do `chai.expect(res.body).to.have...` instead does the report match your expectations?

**Comment by rkpareek** [comment] 2018-07-26 05:01
Yeah, you are right. I posted the expected XML. 
BTW Thanks a lot.

**Comment by clayreimann** [comment] 2018-07-27 16:48
@rkpareek I've got code that sets the attributes as expected in the XML. Haven't gotten time to fix the tests.

Also, @michaelleeallen you'll probably need to update your token in the `travis.yml` after npm invalidated everyone's token a couple weeks ago.

**Comment by michaelleeallen** [comment] 2018-08-07 18:29
I submitted #65 to address the NPM token

**Comment by clayreimann** [comment] 2018-08-09 17:13
@rkpareek This is released in `1.18.0`

**Comment by rkpareek** [comment] 2018-08-10 04:14
Thanks, I got it.

But still stack trace contains both message and type.

**Comment by rkpareek** [comment] 2018-08-10 07:34
still failure does not includes the message and type attributes for recursive test run

**Comment by clayreimann** [comment] 2018-08-10 23:05
Can you run the unit tests for this package and describe how the output should differ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by clayreimann** [comment] 2018-08-29 14:42
@rkpareek Any updates?

**Comment by rkpareek** [comment] 2018-08-30 05:53
Actual Xml output:

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="1.622" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2018-08-30T05:48:17" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="Suite1" timestamp="2018-08-30T05:48:17" tests="1" file="D:\working-directory\automation\Test\test.js" failures="1" time="1.622">
    <testcase name="Suite1 Test Cases-1" time="1.622" classname="Test Cases-1">
      <failure message="actual array is not equal to expected array" type="Error"><![CDATA[Error: actual array is not equal to expected array
    at Object.assertResponse (Test\utility-modules\request-controller.js:123:23)
    at Test\test.js:30:27
    at pass_cb (Test\utility-modules\request-controller.js:86:17)
    at Test.<anonymous> (Test\utility-modules\request-controller.js:89:13)
    at Test.assert (node_modules\supertest\lib\test.js:179:6)
    at assert (node_modules\supertest\lib\test.js:131:12)
    at node_modules\supertest\lib\test.js:128:5
    at Test.Request.callback (node_modules\superagent\lib\node\index.js:718:3)
    at parser (node_modules\superagent\lib\node\index.js:906:18)
    at Stream.res.on (node_modules\superagent\lib\node\parsers\json.js:19:7)
    at Unzip.unzip.on (node_modules\superagent\lib\node\unzip.js:55:12)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)]]></failure>
    </testcase>
  </testsuite>
</testsuites>
```


Expected Xml output:

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="1.622" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2018-08-30T05:48:17" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="Suite1" timestamp="2018-08-30T05:48:17" tests="1" file="D:\working-directory\automation\Test\test.js" failures="1" time="1.622">
    <testcase name="Suite1 Test Cases-1" time="1.622" classname="Test Cases-1">
      <failure message="actual array is not equal to expected array" type="Error"><![CDATA[
    at Object.assertResponse (Test\utility-modules\request-controller.js:123:23)
    at Test\test.js:30:27
    at pass_cb (Test\utility-modules\request-controller.js:86:17)
    at Test.<anonymous> (Test\utility-modules\request-controller.js:89:13)
    at Test.assert (node_modules\supertest\lib\test.js:179:6)
    at assert (node_modules\supertest\lib\test.js:131:12)
    at node_modules\supertest\lib\test.js:128:5
    at Test.Request.callback (node_modules\superagent\lib\node\index.js:718:3)
    at parser (node_modules\superagent\lib\node\index.js:906:18)
    at Stream.res.on (node_modules\superagent\lib\node\parsers\json.js:19:7)
    at Unzip.unzip.on (node_modules\superagent\lib\node\unzip.js:55:12)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)]]></failure>
    </testcase>
  </testsuite>
</testsuites>
```

**Comment by rkpareek** [comment] 2018-08-30 05:56
@clayreimann The CDATA should not contain message and type

**Comment by clayreimann** [comment] 2018-08-30 12:03
@rkpareek those are there because they are part of the stack trace.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rkpareek** [comment] 2018-08-30 12:07
@clayreimann xml reporters does not treat these attributes as part of stacktrace.

**Comment by clayreimann** [comment] 2018-08-31 12:29
Are you talking about a built in xml reporter? The cdata is just `err.stack`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by clayreimann** [comment] 2020-01-11 15:15
Closing as stale

**Closed by clayreimann** 2020-01-11 15:15 UTC
Labels: enhancement
